config/routes.rb
Rails.application.routes.draw do

  scope "(:locale)", locale: /#{I18n.available_locales.join("|")}/ do
  
    resources :signatures
    get 'coin_new/index'
    get 'note_new/index'
    resources :boughts
    resources :patterns
    resources :bonds
    devise_for :users
    # get 'note_collection/index'
    # get 'note_for_sell/index'
    # get 'note_for_sell/show'
    # get 'note_collection/show'
    get 'note_collection/show_currency/:id', to: 'note_collection#show_currency', as: 'show_currency'
    get 'note_collection/show_note/:id', to: 'note_collection#show_note', as: 'show_note'
    get 'note_collection/show_note_user/:id', to: 'note_collection#show_note_user', as: 'show_note_user'
    get 'note_collection/back_show_currency/:id', to: 'note_collection#back_show_currency', as: 'back_show_currency'
    get 'note_collection/show_all_notes/:id', to: 'note_collection#show_all_notes', as: 'show_all_notes'

    get 'note_collection/back_to_country_note_collection/:continent', to: 'note_collection#back_to_country_note_collection', as: 'back_to_country_note_collection'


    
    
    # get 'home/index'
    root 'home#index'
    get 'home/about'
    get 'reports/chart'

    get 'currencies/new/country/currency'

    resources :reports
    resources :countries
    resources :currencies
    resources :notes
    resources :note_for_sell, only: [:index, :show]
    resources :note_sold, only: [:index, :show]
    resources :note_new, only: [:index, :show]
    resources :coin_new, only: [:index, :show]
    resources :note_collection, only: [:index, :show]
    resources :coin_for_sell, only: [:index, :show]
    resources :note_future, only: [:index, :show]
    resources :coin_collection, only: [:index, :show]
    resources :bond_collection, only: [:index, :show]
    get 'coin_collection/show_coins/:id', to: 'coin_collection#show_coins', as: 'show_coins'
    get 'coin_collection/show_details_coin/:id', to:'coin_collection#show_details_coin', as: 'show_details_coin'
    get 'coin_collection/show_coin_user/:id', to: 'coin_collection#show_coin_user', as: 'show_coin_user'
    get 'coin_collection/back_show_currency_coin/:id', to: 'coin_collection#back_show_currency_coin', as: 'back_show_currency_coin'
    

    resources :notes
    get 'notes/note_currencies/:id', to: 'notes#note_currencies', as: 'note_currencies'
    get 'notes/note_show_currency/:id', to: 'notes#note_show_currency', as: 'note_show_currency'
    get 'note_search', to: 'notes#note_search'

    resources :coins
    get 'coins/coin_currencies/:id', to: 'coins#coin_currencies', as: 'coin_currencies'
    get 'coins/coin_show_currency/:id', to: 'coins#coin_show_currency', as: 'coin_show_currency'
    get 'coins/new/:id', to: 'coins#new', as: 'new'
    get 'coin_search', to: 'coins#coin_search'

    # BONDS
  
    get 'bonds/bond_currencies/:id', to: 'bonds#bond_currencies', as: 'bond_currencies'
    get 'bonds/bond_show_currency/:id', to: 'bonds#bond_show_currency', as: 'bond_show_currency'
    get 'bond_search', to: 'bonds#bond_search'

    get 'bond_collection/show_bonds/:id', to: 'bond_collection#show_bonds', as: 'show_bonds'
    get 'bond_collection/back_show_currency_bond/:id', to: 'bond_collection#back_show_currency_bond', as: 'back_show_currency_bond'
    get 'bond_collection/show_bond_user/:id', to: 'bond_collection#show_bond_user', as: 'show_bond_user'


    # get 'bond_collection/show_details_bond/:id', to:'bond_collection#show_details_bond', as: 'show_details_bond'  

    # Note for sell
    get 'note_for_sell_list', to: 'note_for_sell#note_for_sell_list'

    # Note Future
    get 'note_future_list', to: 'note_future#note_future_list'
    get 'note_future/show_note_future/:id', to: 'note_future#show_note_future', as: 'show_note_future'


    resources :countries do
      resources :currencies
    end 

    get 'country_search', to: 'countries#country_search'

    resources :currencies do
      resources :notes
    end  

    resources :currencies do
      resources :coins
    end  
    
    resources :currencies do
      resources :bonds
    end

    resources :charts

    resources :customers
    resources :customers do
      resources :orders
    end

    resources :orders
    resources :settings

    resources :order_items
    resources :orders do
      resources :order_items
    end

    get 'order_items/:id_item/item_pattern/:pattern', to: 'order_items#new', as: 'order_item_pattern'
    get 'order_items_for_sell', to: 'order_items#for_sell'

    # get 'goldapi/index'
    resources :goldapi, only: [:index]

    resources :continents
    resources :currency_units
    resources :countries do
      resources :currency_units
    end

    mount ReportsKit::Engine, at: '/'

  end  
    # APi controller
  
    namespace :api do 
      namespace :v1 do
        resources :country, only: [:index, :show]  
        resources :currencies
      end    
    end
end

app/models/note.rb
class Note < ApplicationRecord
  belongs_to :currency

  validates :making, presence: true
  validates :status, presence: true
  validates :img_type, presence: true

  # validates :price_buy, format: { with: /\A([0-9]{1,4}|[0-9]{1,4}+[\.]?[0-9]{1,2})\z/, message: "Cena musi byc liczba" }
  validates :price_buy ,presence:true, numericality: {only_float: true}
  validates :price_sell ,presence:true, numericality: {only_float: true}

  validates :note_width ,numericality: {only_integer: true}, allow_blank: true
  validates :note_height ,numericality: {only_integer: true}, allow_blank: true

  def self.default_timezone
    :utc
  end

  def to_s
  	note
  end
  def to_s
  	currency
  end
end

app/controllers/notes_controller.rb
class NotesController < ApplicationController
  before_action :set_note, only: [:show, :edit, :update, :destroy]
  before_action :set_role
  before_action :set_role_status, only: [:edit]
  before_action :require_admin_logged_in!, only: [:show, :new, :create, :destroy, :note_show_currency, :note_currencies]

  # require 'List_element'

  include CurrenciesHelper
  include CountriesHelper

  # GET /notes
  # GET /notes.json
  def index
    # @notes = Note.all
    @countries = countries_list
    puts countries_list.size
    @lang = extract_locale
    @search = "note_search"
    puts "TU JESTEM INDEX"
    puts params[:q].to_s
    if(params[:q] == "")
      puts "coś znalazło"
    end
  end

  def note_currencies
    @lang = extract_locale
    puts "$$$$$$$$$$$$$$$$$$$$$$$$$$ TEST NOTE $$$$$$$$$$$$$$$$$$$$$$$$$$$$$$"
    puts params[:id]
    puts params[:pattern]
    @pattern = params[:pattern]
    puts @lang

    
    puts "$$$$$$$$$$$$$$$$$$$$$$$$$$ END TEST $$$$$$$$$$$$$$$$$$$$$$$$$$$$$$"
    @country = Country.find(params[:id])
    @currencies = get_currencies_with_pattern(@country.id, "NOTE")
    if (@currencies.size == 0)
      @pattern = "NOTE"
    else (params[:pattern] != "")
      puts @currencies[0].pattern 
      puts "++++++++++++++++++++++++++++++++++++++++++++++++++++s"
      puts params[:pattern].to_s
      @pattern = @currencies[0].pattern 
    end
  end

  def note_show_currency

    puts "(((((((((((((((((((((TEST NOTE TEST ))))))))))))))))))))))))))))"
    puts params[:id]
    puts params[:country_id]
    puts "(((((((((((((((((((((((((END TEST END)))))))))))))))))))))))"


    puts "############# Note_SHOW_CURRENCY#####################################"
    if (params[:country_id] != nil)        
      @currency = Currency.find(params[:country_id])
      # @collection = @currency.notes.select { |note| note.status == 'KOLEKCJA' }
      # @sale =  @currency.notes.select { |note| note.status == 'FOR SELL' }
      @collection = Note.where(currency_id: params[:country_id]).order(denomination: :asc)
      puts "SHOW TEST WALUTY"
      puts params[:country_id]
      puts params[:id]
      puts "SHOW TEST"        
  else       
      puts "+++++++++++++++++++++++ WALUTY +++++++++++++++++++++++++"
      puts params[:id]      
      @currency = Currency.find(params[:id])   
      @collection = Note.where(currency_id: params[:id]).order(denomination: :asc)   
      puts "+++++++++++++++++++++++++++++++++++++++++++++++++"  
  end
  end

  # GET /notes/1
  # GET /notes/1.json
  def show
    # @notes = Note.find(params[:currency_id])
    # puts "!!!!!!!!!!!!!!!!!TEST!!!!!!!!!!!!!!!!!!"
    # puts @notes
    # puts "!!!!!!!!!!!!!!!!!!TEST!!!!!!!!!!!!!!!!!!!!"
     if (params[:currency_id] != nil)
        
        @note = Note.find(params[:currency_id])
        puts "SHOW TEST"
        puts params[:currency_id]
        puts "SHOW TEST"        
    else       
        puts "++++++++++++++++++++++++++++++++++++++++++++++++!!!!!!!!!!!!!"
        puts params[:id]      
        @note = Note.find(params[:id])  
        puts @note.currency.country.country_en
        @country = @note.currency.country
        puts "+++++++++++++++++++++++++++++++++++++++++++++++++!!!!!!!!!!!!!!"  
    end
  end

  # GET /notes/new
  def new
    @note = Note.new
    @note.price_buy = 0.0
    @note.price_sell = 0.0
    puts "@@@@@@@@@@@@@TEST@@@@@@@@@@@@@@@@@"
    puts params[:currency_id]
    @note.currency_id = params[:currency_id]

    puts @note.currency.country.id
    # @currencies = Currency.where(country_id: @note.currency.country.id, pattern: "NOTE").order(currency_series: :asc)
    @currencies = currency_series(@note, "NOTE")
    puts @currencies.inspect
    puts "@@@@@@@@@@@@@TEST@@@@@@@@@@@@@@@@@"

    @boughts = Bought.all
    @statuses = ElementSelect.statuses
    @makings = ElementSelect.makings
    @img_types = ElementSelect.img_types
    @unit_quantities = ElementSelect.unit_quantities

    @country = @note.currency.country
  end

  def note_search
    begin
      @countries = search_country(params[:q])
      $country_search = @countries
      @lang = extract_locale
      # @search = "note_search"
      # TODO sprawdzić gdzie jest potrzebne @search
      if (params[:q] == "")
        @countries = countries_list
      end
      # @countries = Country.where("country_en ILIKE ?","%" + params[:q] + "%")
      render :index
    rescue
      @countries = $country_search
      @lang = extract_locale
      # @search = "note_search"
      # TODO sprawdzić gdzie jest potrzebne @search
      render :index
    end
  end 

  # GET /notes/1/edit
  def edit
    # @currencies = Currency.where(country_id: @note.currency.country.id, pattern: "NOTE").order(currency_series: :asc)
    @currencies = currency_series(@note, "NOTE")

    @statuses = ElementSelect.statuses
    @makings = ElementSelect.makings
    @img_types = ElementSelect.img_types
    @unit_quantities = ElementSelect.unit_quantities

    @country = @note.currency.country
    curr = currency_series(@note, "NOTE")
    curr.each do |c|
      puts c.currency_series
    end
  end

  # POST /notes
  # POST /notes.json
  def create    
    @note = Note.new(note_params)
    @currencies = currency_series(@note, "NOTE")
    puts @note.inspect
    puts "!!!!!!!!!!!!!!!!!!!!!!!!!!((((((((((((((((())))))))))))))))))))))))!!!!!!!!!!!!!!!!!!!!!!!!!"

    respond_to do |format|
      if @note.save
        @currency = Currency.find(@note.currency_id)
        format.html { redirect_to note_show_currency_path(@currency), notice: 'Note was successfully created.' }
        format.json { render :show, status: :created, location: @note }
      else
        @statuses = ElementSelect.statuses
        @makings = ElementSelect.makings
        @img_types = ElementSelect.img_types
        @unit_quantities = ElementSelect.unit_quantities
        @country = @note.currency.country
        format.html { render :new }
        format.json { render json: @note.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /notes/1
  # PATCH/PUT /notes/1.json
  def update
    puts "!!!!!!!!!!!!!!!!!!!!!!!!!!(((((((((((((((((STATU UPDATE))))))))))))))))))))))))!!!!!!!!!!!!!!!!!!!!!!!!!"
    @currencies = currency_series(@note, "NOTE")
    puts @currencies.inspect
    puts "!!!!!!!!!!!!!!!!!!!!!!!!!!(((((((((((((((((END UPDATE))))))))))))))))))))))))!!!!!!!!!!!!!!!!!!!!!!!!!"
    respond_to do |format|
      if @note.update(note_params)
        if (@note.status == "FUTURE")
          puts "&&&&&&&&&&&&&&&&&TEST FUTURE UPDATE&&&&&&&&&&&&&&&&&&&"
          puts @note.currency.country.id
          @currency = Currency.find(@note.currency_id)
          # format.html { redirect_to note_show_currency_path(@currency), notice: 'Note was successfully updated.' }
          format.html { redirect_to note_future_path(@note.currency.country), notice: t('note_success_update') }

        else
          @currency = Currency.find(@note.currency_id)
          format.html { redirect_to note_show_currency_path(@currency), notice: t('note_success_update') }
          format.json { render :show, status: :ok, location: @note }
        end
      else
        @statuses = ElementSelect.statuses
        @makings = ElementSelect.makings
        @img_types = ElementSelect.img_types
        @unit_quantities = ElementSelect.unit_quantities
        @country = @note.currency.country
        format.html { render :edit }
        format.json { render json: @note.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /notes/1
  # DELETE /notes/1.json
  def destroy
    @currency = Currency.find(@note.currency_id)
    @note.destroy

    respond_to do |format|
      format.html { redirect_to @currency, notice: 'Note was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_note
        @note = Note.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def note_params
      params.require(:note).permit(:currency_id, :denomination, :name_currency, :note_date, :signature_code, :price_buy, :price_sell, 
                                   :quantity, :quality, :status, :description, :img_type, :avers_path, :reverse_path, :series, :making, 
                                   :date_buy_note, :bought, :status_sell, :note_width, :note_height, :unit_quantity, :unit_currency, :visible)
    end

    def set_role
      if (current_user == nil)
          redirect_to root_path
      elsif (current_user.role == 'admin' || current_user.role == 's_user')
          puts "^^^^^^^^^^^^^^^^^^^^^^^^^^^^^TEST^^^^^^^^^^^^^^^^^^^^^^^"
          puts @note.inspect
          puts "^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^END TEST^^^^^^^^^^^^^^^^^"
          return true
      else
          redirect_to root_path
      end
    end

    def set_role_status
      if (current_user == nil)
        redirect_to root_path
      elsif ((current_user.role == 's_user' && @note.status == "FUTURE") || (current_user.role == 'admin'))
        return
      else
        redirect_to root_path
      end
    end
end

app/helpers/notes_helper.rb
module NotesHelper
end

app/views/notes/_form.html.erb
<%= form_with(model: note) do |form| %>
  <% if note.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(note.errors.count, "error") %> prohibited this note from being saved:</h2>

      <ul>
        <% note.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
<% if user_signed_in? && current_user.role == 'admin' %>
  <div class="col field">
    <%= form.label t('activerecord.attributes.currency.currency_series') %>
    <% form.text_field :currency_id, class:"form-control form-control-sm" %>
    <%= form.select :currency_id, @currencies.all.map { |b| [b.currency_series, b.id]}, {:include => ""}, class:"form-control  form-control-sm" %>
  </div>
<% end %>
<div class="container">
  <div class="row row-cols-1 row-cols-sm-2 row-cols-md-3">
    <div class="col-4 field ">
      <%= form.label :date_buy_note %><br/>
       <%= form.date_select :date_buy_note, class:"form-control form-control-sm" %>
    </div>
    <div class="col field">
      <div style="float:left">
        <%= form.label :bought %>
        <% form.text_field :bought, class:"form-control form-control-sm" %>
        <%= form.select :bought, Bought.all.map { |b| [b.name, b.name]}, {:include_blank => "Select(" + t('activerecord.attributes.note.bought') + ")"}, class:"form-control  form-control-sm" %>
      </div>
    </div>
    <div class="col field">
      <% if user_signed_in? && current_user.role == 'admin' %>
        <div style="float:left; margin-top:7%">
          <%= link_to 'Nowe miejsce zakupu', new_bought_path, class:"btn btn-sm btn-primary"%>
        </div>
      <% end %>
    </div>    
  </div>
  <div class="row row-cols-1 row-cols-sm-2 row-cols-md-4">
    <div class="col field">
      <%= form.label :denomination %>
      <%= form.text_field :denomination, class:"form-control form-control-sm", placeholder: t('activerecord.attributes.note.denomination') %>
    </div>
    <div class="col field ">
      <%= form.label :name_currency %>
      <%= form.text_field :name_currency, class:"form-control form-control-sm", placeholder: t('activerecord.attributes.note.name_currency') %>
    </div>
    <div class="col field">
      <%= form.label :series %>
      <%= form.text_field :series, class:"form-control form-control-sm", placeholder: t('activerecord.attributes.note.series') %>
    </div>
    <div class="col field">
      <%= form.label :note_date %>
      <%= form.text_field :note_date, class:"form-control form-control-sm", placeholder: t('activerecord.attributes.note.note_date') %>
    </div>
    <div class="col field">
      <div style="max-width: 60%; float: left;" >
        <%= form.label :quantity %>
        <%= form.number_field :quantity, class:"form-control form-control-sm", placeholder: t('activerecord.attributes.note.quantity') %>
      </div>
      <div style="max-width: 40%; float: right;">
        <%= form.label :unit %> <br/> 
        <% form.text_field :unit_quantity, class:"form-control form-control-sm" %>  
        <%= form.select :unit_quantity, (@unit_quantities.collect { |m| [m[0], m[0]] }), class:"form-control form-control-sm" %>  
      </div>
    </div>
    <% if user_signed_in? && current_user.role == 'admin' %>
      <div class="col field">
        <%= form.label :signature_code %>
        <%= form.number_field :signature_code, class:"form-control form-control-sm", placeholder: t('activerecord.attributes.note.signature_code') %>
      </div>
    <% end %>
    <div class="col field">
      <%= form.label :price_buy %>
      <%= form.text_field :price_buy, class:"form-control form-control-sm"%>
      <% note.errors.messages_for(:price_buy).each do |message| %>
        <div  class="alert alert-danger" role="alert"><%= message %></div>
      <% end %>
    </div>
    <% if user_signed_in? && current_user.role == 'admin' %>
      <div class="col field">
        <%= form.label :price_sell %>
        <%= form.text_field :price_sell, class:"form-control form-control-sm" %>
        <% note.errors.messages_for(:price_sell).each do |message| %>
          <div  class="alert alert-danger" role="alert"><%= message %></div>
        <% end %>
      </div>
      <div class="col field">
        <%= form.label :making %>  
        <% form.text_field :making, class:"form-control form-control-sm" %>  

        <%= form.select :making, (@makings.collect { |m| [m[0], m[0]] }),  {:include_blank => "Select(" + t('activerecord.attributes.note.making') + ")"}, class:"form-control form-control-sm" %>  
        <% note.errors.full_messages_for(:making).each do |message| %>
          <div  class="alert alert-danger" role="alert"><%= message %></div>
        <% end %>   
      </div>
    <% end %>
    
    <div class="col field">
      <%= form.label :quality %>
      <%= form.text_field :quality, class:"form-control form-control-sm", placeholder: t('activerecord.attributes.note.quality') %>
    </div>
    <div class="col field">
      <%= form.label :note_width %>
      <%= form.text_field :note_width, class:"form-control form-control-sm", placeholder: t('activerecord.attributes.note.note_width') %>
      <% note.errors.full_messages_for(:note_width).each do |message| %>
        <div  class="alert alert-danger" role="alert"><%= message %></div>
      <% end %>
    </div>
    <div class="col field">
      <%= form.label :note_height %>
      <%= form.text_field :note_height, class:"form-control form-control-sm", placeholder: t('activerecord.attributes.note.note_height') %>
      <% note.errors.full_messages_for(:note_height).each do |message| %>
        <div  class="alert alert-danger" role="alert"><%= message %></div>
      <% end %>
    </div>
     <% if user_signed_in? && current_user.role == 'admin' %>
      <div class="col field">
        <%= form.label :status %>
        <% form.text_field :status, class:"form-control form-control-sm" %>

        <%= form.select :status, (@statuses.collect { |s| [s[0], s[0]] }),  {:include_blank => "Select(" + t('activerecord.attributes.note.status') + ")"}, class:"form-control form-control-sm"  %>  
        <% note.errors.full_messages_for(:status).each do |message| %>
          <div  class="alert alert-danger" role="alert"><%= message %></div>
        <% end %>
      </div>
        
      <div class="col field">
        <%= form.label :img_type %>
        <% form.text_field :img_type, class:"form-control form-control-sm" %>
  
        <%= form.select :img_type, (@img_types.collect { |img| [img[0], img[0]] }),  {:include_blank => "Select(" + t('activerecord.attributes.note.img_type') + ")"}, class:"form-control form-control-sm"  %>  
        <% note.errors.full_messages_for(:img_type).each do |message| %>
          <div  class="alert alert-danger" role="alert"><%= message %></div>
        <% end %>  
      </div>
      <div class="col field">
        <%= form.label :status_sell %>
        <%= form.text_field :status_sell, class:"form-control form-control-sm", placeholder: t('activerecord.attributes.note.status_sell') %>
      </div>
      <div class="col field" style="background: orange">
        <%= form.label :visible %><br/>
        <%= form.select :visible, [true, false], class:"form-control form-control-sm" %>
      </div>
    <% end %>
    <div class="col col-lg-9 field">
      <%= form.label :description %>
      <%= form.text_area :description, class:"form-control form-control-sm", placeholder: t('activerecord.attributes.note.description') %>
    </div>
    

  </div>
  <% if user_signed_in? && current_user.role == 'admin' %>
    <div class="field">
      <% form.label :avers_path %>
      <%= form.text_field :avers_path, class:"form-control form-control-sm", placeholder: t('activerecord.attributes.note.avers_path') %>
    </div>

    <div class="field">
      <% form.label :reverse_path %>
      <%= form.text_field :reverse_path, class:"form-control form-control-sm", placeholder: t('activerecord.attributes.note.reverse_path') %>
    </div>
  <% end %>
</div>
  <%= render 'renders/image_edit', object: note %>
 
  <div class="container actions">
    <%= form.submit class:"btn btn-sm btn-primary" %>
  </div>
<% end %>

app/views/notes/note_show_currency.html.erb
<h3>NOTE SHOW CURRENCY</h3>

<div class="jumbotron pb-0" >
  <h3 class="display-4">
      <strong>Państwo:</strong>
      <%= @currency.country.country_en %>
  </h3>
  <p class="m-0">
    <strong>Cod:</strong><%= @currency.cod %>  |  
    <strong>Waluta:</strong><%= @currency.currency %>  |  
    <strong>Drobne:</strong><%= @currency.change %>
  </p>
  <p class="m-0">
    <strong>Active:</strong><%= @currency.active %>  |  
    <strong>Data wymiany: </strong><%= @currency.data_exchange %><br/>
    <strong style="color:red">Okres występowania: </strong><%= @currency.currency_series %>
  </p>
  <p class="m-0">
    <strong>Poprzedna waluta:</strong><%= @currency.currency_from %>  |  
    <strong>Przelicznik:</strong><%= @currency.converter %>
  </p>
  <p class="m-0">
    <strong>Description:</strong><%= @currency.description %>
  </p>

  <div class="m-20">
    <%= link_to (render 'renders/button_back'), note_currencies_path(@currency.country_id, 'pattern' => @currency.pattern), class:"btn btn-secondary btn-sm" %>
    <%= link_to 'Add Note', new_currency_note_path(@currency), class:"btn btn-primary btn-sm" %>
    <%= link_to 'Edit currency', edit_currency_path(@currency), class:"btn btn-primary btn-sm", style:"float: right"  %>
  </div>

</div>

<div style="margin-right: 0%; margin-left: 0%;">
    <table class="table table-sm table-striped table-bordered table-hover">
    <thead class="thead-dark">
    <tr>
        <th>Id</th>
        <th>Nominał</th>
        <th>Waluta</th>
        <th>Rok</th>
        <th>SIG</th>
        <th>Status</th>
        <th>Kupno</th>
        <th>Sprzedaż</th>
        <th style="width:30%">Avers/Reverse</th>
        <th></th>
        <th></th>
      </tr>
    </thead>
    <% @collection.each do |note| %>

        <tr>
            <td><%= note.id %></td>
            <td >
              <div style="float: right">
                <% note.denomination %>
                <%= number_with_delimiter(note.denomination , delimiter: " ") %>
              </div>
            </td>
            <td><%= note.name_currency %></td>
            <td><%= note.note_date %></td>
            <td><%= note.signature_code %></td>
            <td><%= note.status %></td>
            <td><%= note.price_buy %></td>
            <td><%= note.price_sell %></td>
            <td>        
                <% if (note.avers_path.length > 80) %>
                <div class="show-note">
                    <%= link_to (image_tag(note.avers_path, :alt => "AVERSE" , style:"width:40%;height:50%")), note_path(note) %>
                    <%= link_to (image_tag(note.reverse_path, :alt => "REVERSE" , style:"width:40%;height:50%")), note_path(note) %>
                </div>
                <% else %>
                    <%= note.avers_path %>
                <%= note.reverse_path %>
                <% end %> 
            </td>
            <td>

 <%#= link_to 'Show', note_path(note), class:"btn btn-info btn-sm" %>

                <%= link_to (render 'renders/button_edit'), edit_note_path(note), class:"btn btn-primary btn-sm" %>
            </td>
            <td>
                <%= link_to (render 'renders/button_delete'), note, method: :delete, data: { confirm: 'Are you sure?' }, class:"btn btn-danger btn-sm", style:"float: right"  %>
            </td>
        </tr>

    <% end %>
    
    </table>
</div>

app/views/notes/show.html.erb
<p id="notice"><%= notice %></p>
<div class="jumbotron">
  <div class="container row">
		<div class="col-md-2">
		</div>
		<div class="col-md-8">
			<%= render 'renders/show_flag_country' %>
		</div>			
		<div class="col-md-2">
		</div>
  </div>

  <%= render 'note_collection/show_note' %>
  <div>
    <% if user_signed_in? && current_user.role == 'admin' %>
      <div style="float: left">
          <%= link_to (render 'renders/button_back'), note_show_currency_path(@note.currency_id), class:"btn btn-secondary btn-sm" %>
          <%= link_to (render 'renders/button_edit'), edit_note_path(@note), class:"btn btn-primary btn-sm" %> 
      </div>
    <% end %>
    <% if @note.status == "KOLEKCJA" %>
      <div style="float:right">
            <%= link_to (render 'renders/button_back'), show_note_path(@note.currency_id), class:"btn btn-outline-info btn-sm" %> 
      </div>
    <% end %>
    <% if @note.status == "FOR SELL" %>
      <div style="float:right">
            <%= link_to (render 'renders/button_back') + " Back To List", note_for_sell_list_path, class:"btn btn-outline-info btn-sm" %> 
      </div>
    <% end %>
  </div>
</div>