config/routes.rb
Rails.application.routes.draw do

  scope "(:locale)", locale: /#{I18n.available_locales.join("|")}/ do
  
    resources :signatures
    get 'coin_new/index'
    get 'note_new/index'
    resources :boughts
    resources :patterns
    resources :bonds
    devise_for :users
    # get 'note_collection/index'
    # get 'note_for_sell/index'
    # get 'note_for_sell/show'
    # get 'note_collection/show'
    get 'note_collection/show_currency/:id', to: 'note_collection#show_currency', as: 'show_currency'
    get 'note_collection/show_note/:id', to: 'note_collection#show_note', as: 'show_note'
    get 'note_collection/show_note_user/:id', to: 'note_collection#show_note_user', as: 'show_note_user'
    get 'note_collection/back_show_currency/:id', to: 'note_collection#back_show_currency', as: 'back_show_currency'
    get 'note_collection/show_all_notes/:id', to: 'note_collection#show_all_notes', as: 'show_all_notes'

    get 'note_collection/back_to_country_note_collection/:continent', to: 'note_collection#back_to_country_note_collection', as: 'back_to_country_note_collection'


    
    
    # get 'home/index'
    root 'home#index'
    get 'home/about'
    get 'reports/chart'

    get 'currencies/new/country/currency'

    resources :reports
    resources :countries
    resources :currencies
    resources :notes
    resources :note_for_sell, only: [:index, :show]
    resources :note_sold, only: [:index, :show]
    resources :note_new, only: [:index, :show]
    resources :coin_new, only: [:index, :show]
    resources :note_collection, only: [:index, :show]
    resources :coin_for_sell, only: [:index, :show]
    resources :note_future, only: [:index, :show]
    resources :coin_collection, only: [:index, :show]
    resources :bond_collection, only: [:index, :show]
    get 'coin_collection/show_coins/:id', to: 'coin_collection#show_coins', as: 'show_coins'
    get 'coin_collection/show_details_coin/:id', to:'coin_collection#show_details_coin', as: 'show_details_coin'
    get 'coin_collection/show_coin_user/:id', to: 'coin_collection#show_coin_user', as: 'show_coin_user'
    get 'coin_collection/back_show_currency_coin/:id', to: 'coin_collection#back_show_currency_coin', as: 'back_show_currency_coin'
    

    resources :notes
    get 'notes/note_currencies/:id', to: 'notes#note_currencies', as: 'note_currencies'
    get 'notes/note_show_currency/:id', to: 'notes#note_show_currency', as: 'note_show_currency'
    get 'note_search', to: 'notes#note_search'

    resources :coins
    get 'coins/coin_currencies/:id', to: 'coins#coin_currencies', as: 'coin_currencies'
    get 'coins/coin_show_currency/:id', to: 'coins#coin_show_currency', as: 'coin_show_currency'
    get 'coins/new/:id', to: 'coins#new', as: 'new'
    get 'coin_search', to: 'coins#coin_search'

    # BONDS
  
    get 'bonds/bond_currencies/:id', to: 'bonds#bond_currencies', as: 'bond_currencies'
    get 'bonds/bond_show_currency/:id', to: 'bonds#bond_show_currency', as: 'bond_show_currency'
    get 'bond_search', to: 'bonds#bond_search'

    get 'bond_collection/show_bonds/:id', to: 'bond_collection#show_bonds', as: 'show_bonds'
    get 'bond_collection/back_show_currency_bond/:id', to: 'bond_collection#back_show_currency_bond', as: 'back_show_currency_bond'
    get 'bond_collection/show_bond_user/:id', to: 'bond_collection#show_bond_user', as: 'show_bond_user'


    # get 'bond_collection/show_details_bond/:id', to:'bond_collection#show_details_bond', as: 'show_details_bond'  

    # Note for sell
    get 'note_for_sell_list', to: 'note_for_sell#note_for_sell_list'

    # Note Future
    get 'note_future_list', to: 'note_future#note_future_list'
    get 'note_future/show_note_future/:id', to: 'note_future#show_note_future', as: 'show_note_future'


    resources :countries do
      resources :currencies
    end 

    get 'country_search', to: 'countries#country_search'

    resources :currencies do
      resources :notes
    end  

    resources :currencies do
      resources :coins
    end  
    
    resources :currencies do
      resources :bonds
    end

    resources :charts

    resources :customers
    resources :customers do
      resources :orders
    end

    resources :orders
    resources :settings

    resources :order_items
    resources :orders do
      resources :order_items
    end

    get 'order_items/:id_item/item_pattern/:pattern', to: 'order_items#new', as: 'order_item_pattern'
    get 'order_items_for_sell', to: 'order_items#for_sell'

    # get 'goldapi/index'
    resources :goldapi, only: [:index]

    resources :continents
    resources :currency_units
    resources :countries do
      resources :currency_units
    end

    mount ReportsKit::Engine, at: '/'

  end  
    # APi controller
  
    namespace :api do 
      namespace :v1 do
        resources :country, only: [:index, :show]  
        resources :currencies
      end    
    end
end

app/models/currency.rb
class Currency < ApplicationRecord
  belongs_to :country
  has_many :notes
  has_many :coins
  has_many :bonds

  validates :pattern, presence: true

  def self.default_timezone
    :utc
  end

  def to_s
  	cod.to_s
  end
end

app/controllers/currencies_controller.rb
class CurrenciesController < ApplicationController
  before_action :set_currency, only: [:show, :edit, :update, :destroy]
  before_action :require_admin_logged_in!

  # GET /currencies
  # GET /currencies.json
  def index
    @currencies = Currency.all
  end

  # GET /currencies/1
  # GET /currencies/1.json
  def show
   
    if (params[:country_id] != nil)
        
        @currency = Currency.find(params[:country_id])
        # @collection = @currency.notes.select { |note| note.status == 'KOLEKCJA' }
        # @sale =  @currency.notes.select { |note| note.status == 'FOR SELL' }
        @collection = Note.where(currency_id: params[:country_id])
        puts "SHOW TEST WALUTY"
        puts params[:country_id]
        puts params[:id]
        puts "SHOW TEST"        
    else       
        puts "+++++++++++++++++++++++ WALUTY +++++++++++++++++++++++++"
        puts params[:id]      
        @currency = Currency.find(params[:id])   
        @collection = Note.where(currency_id: params[:id])   
        puts "+++++++++++++++++++++++++++++++++++++++++++++++++"  
    end
    @notes = Note.where("status = 'KOLEKCJA'")
    puts @notes.inspect
  end

  # GET /currencies/new
  def new
    @currency = Currency.new
    puts "@@@@@@@@@@@@@TEST@@@@@@@@@@@@@@@@@"
    puts params[:country_id]
    puts params[:pattern]
    @currency.pattern = params[:pattern]
    @currency.country_id = params[:country_id]
    puts "@@@@@@@@@@@@@TEST@@@@@@@@@@@@@@@@@"
    @patterns = Pattern.all

  end

  # GET /currencies/1/edit
  def edit
  end

  # POST /currencies
  # POST /currencies.json
  def create
    # @country = Country.find(params[:country_id])
    # @currency = @country.currencies.create(curency_params)
    @currency = Currency.new(currency_params)
    puts "%%%%%%%%%%%^^^^^^^^^^^^^^^^^^^TEST^^^^^^^^^^^^^^^^^^^^%%%%%%%%%%%%%%%%%%%%%%%%%%"
    puts @currency.pattern
    @pattern = @currency.pattern
    puts "%%%%%%%%%%%%%%%%%^^^^^^^^^^^^END^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^%%%%%%%%%%%%%%%%%%%%"
    respond_to do |format|
      if @currency.save
        @country = @currency.country
        if (@currency.pattern == "NOTE")
          puts "TO JEST BANKNOT"
          format.html { redirect_to note_currencies_path(@country, 'pattern' => @currency.pattern), notice: t('currency_create') }
        end
        if (@currency.pattern == "COIN")
          puts "TO JES MONETA"
          format.html { redirect_to coin_currencies_path(@country, 'pattern' => @currency.pattern), notice: t('currency_create') }
        end
        if (@currency.pattern == "BOND")
          puts "TO JES OBLIGACJA"
          format.html { redirect_to bond_currencies_path(@country, 'pattern' => @currency.pattern), notice: t('currency_create') }
        end
        # format.html { redirect_to @country, notice: 'Currency was successfully created.' }
        # format.json { render :show, status: :created, location: @currency }
      else
        format.html { render :new }
        format.json { render json: @currency.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /currencies/1
  # PATCH/PUT /currencies/1.json
  def update
    respond_to do |format|
      if @currency.update(currency_params)
         @country = @currency.country
        if (@currency.pattern == "NOTE")
          puts "TO JES BANKNOT"
          format.html { redirect_to note_currencies_path(@country, 'pattern' => @currency.pattern), notice: t('currency_update') }
        end
        if (@currency.pattern == "COIN")
          puts "TO JES MONETA"
          format.html { redirect_to coin_currencies_path(@country, 'pattern' => @currency.pattern), notice: t('currency_update') }
        end
        if (@currency.pattern == "BOND")
          puts "TO JES OBLIGACJA"
          format.html { redirect_to bond_currencies_path(@country, 'pattern' => @currency.pattern), notice: t('currency_update') }
        end
        # format.html { redirect_to @country, notice: 'Currency was successfully updated.' }
        # format.json { render :show, status: :ok, location: @currency }
      else
        format.html { render :edit }
        format.json { render json: @currency.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /currencies/1
  # DELETE /currencies/1.json
  def destroy
    @country = @currency.country
    # @coins = Coin.where(currency_id: @currency.id)
    # @notes = Note.where(currency_id: @currency.id)
    # @bonds = Bond.where(currency_id: @currency.id)
    if (@currency.pattern == "COIN")
      @items = Coin.where(currency_id: @currency.id)
    elsif (@currency.pattern == "BOND")
      @items = Bond.where(currency_id: @currency.id)
    elsif (@currency.pattern == "NOTE")
      @items = Note.where(currency_id: @currency.id)
    else
      @items = nil
    end
    if (@items.size == 0)
      @currency.destroy 
      respond_to do |format|
        if (@currency.pattern == "COIN")
          format.html { redirect_to coin_currencies_path(@country, 'pattern' => @currency.pattern), notice: t('currency_delete') }
        end
        if (@currency.pattern == "BOND")
          format.html { redirect_to bond_currencies_path(@country, 'pattern' => @currency.pattern), notice: t('currency_delete') }
        end
        if (@currency.pattern == "NOTE")
          format.html { redirect_to note_currencies_path(@country, 'pattern' => @currency.pattern), notice: t('currency_delete') }
        end  
          format.html { redirect_to @country, notice: 'Currency was successfully destroyed.' }
          format.json { head :no_content }
        end 
      else
        respond_to do |format|
          if (@currency.pattern == "COIN")
            format.html { redirect_to coin_currencies_path(@country, 'pattern' => @currency.pattern), alert: t('currency_not_empty', items: @items.size.to_s) }
          end
          if (@currency.pattern == "BOND")
            format.html { redirect_to bond_currencies_path(@country, 'pattern' => @currency.pattern), alert: t('currency_not_empty', items: @items.size.to_s) }
          end
          if (@currency.pattern == "NOTE")
            format.html { redirect_to note_currencies_path(@country, 'pattern' => @currency.pattern), alert: t('currency_not_empty', items: @items.size.to_s) }
          end
            format.html { redirect_to @country, notice: 'Currency was successfully destroyed.' }
            format.json { head :no_content }
          end 
      end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_currency
      @currency = Currency.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def currency_params
      params.require(:currency).permit(:country_id, :cod, :currency, :change, :active, :data_exchange, :currency_from, :converter, :description, :pattern, :currency_series)
    end
end

app/helpers/currencies_helper.rb
module CurrenciesHelper
    def get_currencies_with_pattern(country_id, pattern)
        Currency.where(country_id: country_id, pattern: pattern).order(currency_series: :asc)
    end

    def countries_list
        Country.all.order(country_en: :asc)
    end

    def currency_series(object, pattern)
        currencies = Currency.where(country_id: object.currency.country.id, pattern: pattern).order(currency_series: :asc)
    end
end

app/views/currencies/_form.html.erb
<div class="jumbotron", style="padding-top:5px">
 <%= form_with(model: currency) do |form| %>
  <% if currency.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(currency.errors.count, "error") %> prohibited this currency from being saved:</h2>

      <ul>
        <% currency.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div style="text-align:center">
    <h3><%= @currency.country.country_en %></h3>
  </div>
  <div class="field ">
    <%= form.label :country_id %>
    <%= form.text_field :country_id, value:@currency.country_id %>
  </div>
  <table class="table table-striped table-bordered table-hover">
    <tr>
      <td>
        <div class="field ">
          <%= form.label :cod %>
          <%= form.text_field :cod, class:"form-control form-control-sm", placeholder: t('activerecord.attributes.currency.cod')%>
        </div>
      </td>
      <td>
        <div class="field ">
          <%= form.label :pattern %>
          <%= form.select :pattern, Pattern.all.map { |p| [p.name_en, p.name_en]}, {:include_blank => "Select(" + t('activerecord.attributes.currency.pattern') +")"}, class:"form-control form-control-sm" %>
          <% currency.errors.full_messages_for(:pattern).each do |message| %>
            <div style="color:red" ><%= message %></div>
          <% end %>
        </div>

      </td>
      <td>
        <div class="field ">
          <%= form.label :currency %>
         <%= form.text_field :currency, class:"form-control form-control-sm", placeholder: t('activerecord.attributes.currency.currency') %>
        </div>
      </td>
    </tr>
    <tr>
      <td>
        <div class="field ">
          <%= form.label :change %>
          <%= form.text_field :change, class:"form-control form-control-sm", placeholder:t('activerecord.attributes.currency.change') %>
        </div>
      </td>
      <td>
        <div class="field ">
          <%= form.label :active %>
          <%= form.number_field :active, class:"form-control form-control-sm", placeholder:t('activerecord.attributes.currency.active') %>
        </div>
      </td>
      <td>
        <div class="field">
          <%= form.label :data_exchange %>
          <%= form.text_field :data_exchange, class:"form-control form-control-sm", placeholder: t('activerecord.attributes.currency.data_exchange') %>
        </div>
      </td>
    </tr>
    <tr>
      <td colspan="3">
        <div class="field">
          <%= form.label :currency_series %>
          <%= form.text_field :currency_series, class:"form-control form-control-sm", placeholder: t('activerecord.attributes.currency.currency_series') %>
        </div>
      </td>
    </tr>
    <tr>
      <td>
        <div class="field ">
          <%= form.label :currency_from %>
          <%= form.text_field :currency_from, class:"form-control form-control-sm", placeholder: t('activerecord.attributes.currency.currency_from') %>
        </div>
      </td>
      <td>
        <div class="field ">
          <%= form.label :converter %>
          <%= form.text_field :converter, class:"form-control form-control-sm", placeholder: t('activerecord.attributes.currency.converter') %>
        </div>
      </td>
    </tr>
  </table>  

  <div class="field ">
    <%= form.label :description %>
    <%= form.text_area :description, class:"form-control form-control-sm", placeholder: t('activerecord.attributes.currency.description') %>
  </div>

  <div class="actions">
    <%= form.submit class:"btn btn-primary" %>
  </div>
<% end %>

</div>

app/views/currencies/edit.html.erb
<div  class="card text-center text-white bg-info">
  <div class="header">
    <h3><%= t('edit_currency') %></h3>
  </div>
</div>

<%= render 'form', currency: @currency %>

<%
=begin%>
 <%= link_to 'Show', @currency, class:"btn btn-secondary" %> 

 <%= link_to 'Back', country_path(@currency.country_id), class:"btn btn-dark" %> 
<%
=end%>
<br/>

app/views/currencies/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Currencies to juz jest nie potrzebne jak sie pojawi dać znać(do usunięcia)</h1>

app/views/currencies/new.html.erb
<div  class="card text-center text-white bg-primary">
  <div class="header">
    <h3><%= t('new_currency') %> <%= @currency.pattern %></h3>
  </div>
</div>

<%= render 'form', currency: @currency %>

<%
=begin%>
 <%= link_to 'Back', country_path(@currency.country_id), class:"btn btn-dark" %> 
<%
=end%>

app/views/currencies/show.html.erb
<p id="notice"><%= notice %></p>
<h3 style="color:red"> WIDOK DO USUNIĘCIA</h3>
<div class="jumbotron">
  <h3 class="display-4">
      <strong>Państwo:</strong>
      <%= @currency.country.country_en %>
  </h3>
  <p>
    <strong>Id:</strong><%= @currency.id %> | 
    <strong>Cod:</strong><%= @currency.cod %>  |  
    <strong>Waluta:</strong><%= @currency.currency %>  |  
    <strong>Drobne:</strong><%= @currency.change %>
  </p>
  <p>
    <strong>Active:</strong><%= @currency.active %>  |  
    <strong>Data wymiany: </strong><%= @currency.data_exchange %> | 
    <strong style="color:red">Okres występowania: </strong><%= @currency.currency_series %>
  </p>
  <p>
    <strong>Poprzedna waluta:</strong><%= @currency.currency_from %>  |  
    <strong>Przelicznik:</strong><%= @currency.converter %>
  </p>
  <p>
    <strong>Description:</strong><%= @currency.description %>
  </p>
  <!-- <hr class="my-4"> -->
 <!--  <p>It uses utility classes for typography and spacing to space content out within the larger container.</p>
  <a class="btn btn-primary btn-lg" href="#" role="button">Learn more</a> -->
  <%= link_to 'Edit', edit_currency_path(@currency), class:"btn btn-secondary" %> 
  <!-- <%= link_to 'Back', currencies_path(@currency) %> -->
  <%= link_to 'Back', country_path(@currency.country_id), class:"btn btn-dark" %>
  <%= link_to 'Add Note', new_currency_note_path(@currency), class:"btn btn-secondary" %>

</div>

<div style="margin-right: -20%; margin-left: -20%;">
  <h2>Banknoty</h2>
  <table class="table table-striped table-bordered table-hover">
    <thead class="thead-dark">
    <tr>
        <th>Id</th>
        <th>Nominał</th>
        <th>Waluta</th>
        <th>Rok</th>
        <th>Materiał</th>
        <th>SIG</th>
        <th>Status</th>
        <th>Kupno</th>
        <th>Sprzedaż</th>
        <th style="width:30%">Avers/Revers</th>
        
        <th ></th>
      </tr>
    </thead>
    <% @collection.each do |note| %>

      <% if note.avers_path.length < 200 %>
        <tr style="background-color:lightskyblue">
          <td><%= note.id %></td>
          <td><%= note.denomination %></td>
          <td><%= note.name_currency %></td>
          <td><%= note.note_date %></td>
          <td><%= note.making %></td>
          <td><%= note.signature_code %></td>
          <td><%= note.status %></td>
          <td><%= note.price_buy %></td>
          <td><%= note.price_sell %></td>
          <td>        
        	<% if (note.avers_path.length > 200) %>
             <div class="show-note">
                <%= image_tag(note.avers_path, :alt => "AVERSE" , style:"width:40%;height:50%") %>
                <%= image_tag(note.reverse_path, :alt => "REVERSE" , style:"width:40%;height:50%") %>
              </div>
            <% else %>
            	<%= note.avers_path %>
              <%= note.reverse_path %>
            <% end %> 
        </td>
       
          <td>
            <%= link_to 'Show', currency_note_path(note), class:"btn btn-info" %> 
            <%= link_to 'Edit', edit_note_path(note), class:"btn btn-primary" %>
            <%= link_to 'Destroy', note, method: :delete, data: { confirm: 'Are you sure?' }, class:"btn btn-danger", style:"float: right" %>
          </td>
        </tr>
      <% else %>
      <tr >
          <td><%= note.id %></td>
          <td><%= note.denomination %></td>
          <td><%= note.name_currency %></td>
          <td><%= note.note_date %></td>
          <td><%= note.making %></td>
          <td><%= note.signature_code %></td>
          <td><%= note.status %></td>
          <td><%= note.price_buy %></td>
          <td><%= note.price_sell %></td>
          <td style="padding:0">        
            <% if (note.avers_path.length > 200) %>
              <div class="show-note">
                <%= image_tag(note.avers_path, :alt => "AVERSE" , style:"width:40%;height:50%") %>
                <%= image_tag(note.reverse_path, :alt => "REVERSE" , style:"width:40%;height:50%") %>
              </div>
              <% else %>
                <%= note.avers_path %>
              <% end %> 
          </td>
          
          <td><%= link_to 'Show', currency_note_path(note), class:"btn btn-info btn-sm" %> 
              <%= link_to 'Edit', edit_note_path(note), class:"btn btn-primary btn-sm" %>
              <%= link_to 'Destroy', note, method: :delete, data: { confirm: 'Are you sure?' }, class:"btn btn-danger btn-sm", style:"float: right" %>
          </td>
        </tr>
        <% end %>
    <% end %>
    
  </table>
</div>