config/routes.rb
Rails.application.routes.draw do

  scope "(:locale)", locale: /#{I18n.available_locales.join("|")}/ do
  
    resources :signatures
    get 'coin_new/index'
    get 'note_new/index'
    resources :boughts
    resources :patterns
    resources :bonds
    devise_for :users
    # get 'note_collection/index'
    # get 'note_for_sell/index'
    # get 'note_for_sell/show'
    # get 'note_collection/show'
    get 'note_collection/show_currency/:id', to: 'note_collection#show_currency', as: 'show_currency'
    get 'note_collection/show_note/:id', to: 'note_collection#show_note', as: 'show_note'
    get 'note_collection/show_note_user/:id', to: 'note_collection#show_note_user', as: 'show_note_user'
    get 'note_collection/back_show_currency/:id', to: 'note_collection#back_show_currency', as: 'back_show_currency'
    get 'note_collection/show_all_notes/:id', to: 'note_collection#show_all_notes', as: 'show_all_notes'

    get 'note_collection/back_to_country_note_collection/:continent', to: 'note_collection#back_to_country_note_collection', as: 'back_to_country_note_collection'


    
    
    # get 'home/index'
    root 'home#index'
    get 'home/about'
    get 'reports/chart'

    get 'currencies/new/country/currency'

    resources :reports
    resources :countries
    resources :currencies
    resources :notes
    resources :note_for_sell, only: [:index, :show]
    resources :note_sold, only: [:index, :show]
    resources :note_new, only: [:index, :show]
    resources :coin_new, only: [:index, :show]
    resources :note_collection, only: [:index, :show]
    resources :coin_for_sell, only: [:index, :show]
    resources :note_future, only: [:index, :show]
    resources :coin_collection, only: [:index, :show]
    resources :bond_collection, only: [:index, :show]
    get 'coin_collection/show_coins/:id', to: 'coin_collection#show_coins', as: 'show_coins'
    get 'coin_collection/show_details_coin/:id', to:'coin_collection#show_details_coin', as: 'show_details_coin'
    get 'coin_collection/show_coin_user/:id', to: 'coin_collection#show_coin_user', as: 'show_coin_user'
    get 'coin_collection/back_show_currency_coin/:id', to: 'coin_collection#back_show_currency_coin', as: 'back_show_currency_coin'
    

    resources :notes
    get 'notes/note_currencies/:id', to: 'notes#note_currencies', as: 'note_currencies'
    get 'notes/note_show_currency/:id', to: 'notes#note_show_currency', as: 'note_show_currency'
    get 'note_search', to: 'notes#note_search'

    resources :coins
    get 'coins/coin_currencies/:id', to: 'coins#coin_currencies', as: 'coin_currencies'
    get 'coins/coin_show_currency/:id', to: 'coins#coin_show_currency', as: 'coin_show_currency'
    get 'coins/new/:id', to: 'coins#new', as: 'new'
    get 'coin_search', to: 'coins#coin_search'

    # BONDS
  
    get 'bonds/bond_currencies/:id', to: 'bonds#bond_currencies', as: 'bond_currencies'
    get 'bonds/bond_show_currency/:id', to: 'bonds#bond_show_currency', as: 'bond_show_currency'
    get 'bond_search', to: 'bonds#bond_search'

    get 'bond_collection/show_bonds/:id', to: 'bond_collection#show_bonds', as: 'show_bonds'
    get 'bond_collection/back_show_currency_bond/:id', to: 'bond_collection#back_show_currency_bond', as: 'back_show_currency_bond'
    get 'bond_collection/show_bond_user/:id', to: 'bond_collection#show_bond_user', as: 'show_bond_user'


    # get 'bond_collection/show_details_bond/:id', to:'bond_collection#show_details_bond', as: 'show_details_bond'  

    # Note for sell
    get 'note_for_sell_list', to: 'note_for_sell#note_for_sell_list'

    # Note Future
    get 'note_future_list', to: 'note_future#note_future_list'
    get 'note_future/show_note_future/:id', to: 'note_future#show_note_future', as: 'show_note_future'


    resources :countries do
      resources :currencies
    end 

    get 'country_search', to: 'countries#country_search'

    resources :currencies do
      resources :notes
    end  

    resources :currencies do
      resources :coins
    end  
    
    resources :currencies do
      resources :bonds
    end

    resources :charts

    resources :customers
    resources :customers do
      resources :orders
    end

    resources :orders
    resources :settings

    resources :order_items
    resources :orders do
      resources :order_items
    end

    get 'order_items/:id_item/item_pattern/:pattern', to: 'order_items#new', as: 'order_item_pattern'
    get 'order_items_for_sell', to: 'order_items#for_sell'

    # get 'goldapi/index'
    resources :goldapi, only: [:index]

    resources :continents
    resources :currency_units
    resources :countries do
      resources :currency_units
    end

    mount ReportsKit::Engine, at: '/'

  end  
    # APi controller
  
    namespace :api do 
      namespace :v1 do
        resources :country, only: [:index, :show]  
        resources :currencies
      end    
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  include HomeHelper
  include ApiMetalHelper


  def index
    # api_metal
    # api_metal_console
  	# @title = "test pecunia"

  	# @data = "my_reports3"
  	# # @dataChart = "bar"

  	# @chart = Chart.all
    # @report = Report.all
  	# select_char
    # select_report

  

  	# puts "!!!!!!!!!!TEST!!!!!!!!!!!!"
   #  puts params[:report_name]
  	# puts params[:chart_name]
  	# puts "!!!!!!!!!!TEST!!!!!!!!!!!!"   
  
    @exchange_rate = ExchangeRate.new
    url = 'https://api.nbp.pl/api/exchangerates/tables/a/?format=json'
    @response_code = response_code(url)
    if (@response_code == "200")
      @exchange = @exchange_rate.rate(url)
    else
      @response_code
    end

    # RATE GOLD
    puts "\n\n $$$$$$$$$$$$$$$$$$$$$ RATE GOLD $$$$$$$$$$$$$$$$$$$$$$$$$$$$"
    url_gold = 'http://api.nbp.pl/api/cenyzlota/last/11/?format=json'
    @response_code_gold = response_code(url_gold)
    @rate_gold = @exchange_rate.rate_gold(url_gold)

    # ------------------ TEST CURRENCY COD pobieranei z bazy -----------------------------

    # _________________________TEST VIEW___________________________________________

    puts "+++++++++++++++++++++++++TEST VIEWS +++++++++++++++++++++++++++++++++++"

    # @view = VItemInfo.all
    #
    # @view.each do |v|
    #   puts v.inspect
    # end


    puts "+++++++++++++++++++++++++++++++END TEST++++++++++++++++++++++++++++++++++"

  end

  def about
    # api_metal
    # api_metal_console
  end

  # private
	#   def select_char
	#   	if (params[:chart_name] == nil || params[:chart_name] == "")
  # 		@dataChart = "bar"
  # 	else
  # 		@dataChart = params[:chart_name]
  		
  # 	end
	#   end

  #   private
  #   def select_report
  #     if (params[:report_name] == nil || params[:report_name] == "")
  #      @data = "my_reports"
  #     # puts "*******************************TEST************************"
  #     # puts @data
  #     # puts "*******************************TEST************************"
    
  #   else
  #      @data = params[:report_name]
  #     puts "$$$$$$$$$$$$!!!!!!!!!!TEST!!!!!!!!!!!!"
  #     # puts @data
  #     @report = Report.where(report: (params[:report_name]))
  #     puts @report
  #     @data_name = @report
  #     # puts @data_name
  #     puts "$$$$$$$$$$$!!!!!!!!!!TEST!!!!!!!!!!!!"
  #   end
  #   end

    
end

app/helpers/home_helper.rb
module HomeHelper
    def response_code(uri)
        resp = Net::HTTP.get_response(URI.parse(uri))

        printf " ---------------------------------------------------------------------------\n"
        printf " |%-10s |%-25s |%-34s| \n","code", "message", "class name"
        printf " ---------------------------------------------------------------------------\n"
        printf " |%-10s |%-25s |%-34s| \n",resp.code, resp.message, resp.class.name
        printf " ------------------------------------------------------------------------------------------\n"
        # url = URI("https://pecunia-rails.herokuapp.com")
        # res = Net::HTTP.get_response(url)
        # puts res['Set-Cookie']
        # puts resp.get_fields('set-cookie')
        # puts res.to_hash['set-cookie']
        # puts "Headers: #{resp.to_hash.inspect}"
        resp.to_hash.each do |h|
            printf " |%-30s |%55s |\n",h[0], h[1]
            puts " ------------------------------------------------------------------------------------------\n"
        end
        # # puts resp.to_hash.inspect
        # puts res.to_hash.inspect
        return resp.code
    end

    def percentage_change(i, j)
        if (j != nil)
            return ((j/i)-1)*-100
        else
            return 1
        end
    end

    def split_code(string_code)
        code_list = string_code.gsub(/\s+/, "").split(",")  #Usuwanie wszystkich spacji i dzielenie po przecinku do tabicy
        return code_list.map!(&:upcase)
    end
end

app/views/home/_api_metal.html.erb
<% if @api_metal_time_update.cod == 200 && @api_metal_time_update.cod !=nil %>
  <div style="background: #2E2F30; color: white; font-size: 12px; text-align: center">
<!--      <spam>Update: </spam>-->
    <%= Time.at(@api_metal_time_update.timestamp/1000).strftime("%Y-%m-%d  %H:%M:%S") %>
    <% @api_metal_time_update.metals.each do |metal| %>
      <% if metal.name != "palladium" %>
        <spam>  |  <%= metal.name %> :</spam> <span style="color:orange"><%= metal.price %></span>$
      <% end %>
    <% end %>
  </div>
<% end %>

app/views/home/_footer.html.erb
<footer class="panel-footer bg-light text-center text-sm-start">
  <!-- Copyright -->
  <div class="text-center p-1" style="background-color: rgba(0, 0, 0, 0.2)">
    © 2021 Copyright: PECUNIA
    <!-- <a class="text-dark" href="https://mdbootstrap.com/">MDBootstrap.com</a> -->
  </div>
  <!-- Copyright -->
</footer>

app/views/home/_header.html.erb
<nav class="navbar navbar-expand-lg navbar-dark bg-dark" style="padding-block: 0;">
	<%= link_to 'Pecunia', root_path, class:"navbar-brand" %>

 <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button> 
  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
    <% if user_signed_in? && current_user.role == 'admin' %>
      <li>          
            <div class="dropdown nav-link">
              <button class="dropbtn dropdown-toggle"><%= t 'menu.country.country' %></button>
                <div class="dropdown-content">
                  <%= link_to t('menu.country.add_country'), new_country_path, class:"nav-link" %>
                  <%= link_to t('menu.country.countries'), countries_path, class:"nav-link" %>             
                </div>
            </div>        
      </li>
    <% end %> 
 
      <li> 
        <% if user_signed_in? %>
          <div class="dropdown nav-link ">
            <button class="dropbtn dropdown-toggle"><%= t 'menu.note.note' %></button>
            <div class="dropdown-content ">
              <% if user_signed_in? && current_user.role == 'admin' %>
                <%= link_to t('menu.note.add_note'), notes_path, class:"nav-link" %>
                <%= link_to t('menu.note.new_notes'), note_new_index_path, class:"nav-link" %>
                <%= link_to t('menu.note.note_sold'), note_sold_index_path, class:'nav-link' %>
                <%= link_to t('menu.note.note_for_sell_list'), note_for_sell_list_path, class:'nav-link' %>
              <% end %>
              <% if user_signed_in? %>
                  <%= link_to t('menu.note.note_for_sell'), note_for_sell_index_path, class:"nav-link" %>
                  <%= link_to t('menu.note.collection'), note_collection_index_path, class:"nav-link" %>
              <% end %>
              
            </div>
          </div>
        <% end %>
      </li>

      <li class="nav-item"> 
        <% if user_signed_in? %>
          <div class="dropdown nav-link ">
            <button class="dropbtn dropdown-toggle"><%= t 'menu.coin.coin' %></button>
              <div class="dropdown-content">
              <% if user_signed_in? && current_user.role == 'admin' %>
                <%= link_to t('menu.coin.add_coin'), coins_path, class:"nav-link" %> 
                <%= link_to t('menu.coin.new_coins'), coin_new_index_path, class:"nav-link" %>            
              <% end %>
              <% if user_signed_in? %>
                 <%= link_to t('menu.coin.coin_for_sell'), coin_for_sell_index_path, class:"nav-link" %>
                 <%= link_to t('menu.coin.collection'), coin_collection_index_path, class:"nav-link" %>
              <% end %>
                
            </div>
          </div>
        <% end %>
      </li>
       <li class="nav-item"> 
        <% if user_signed_in? %>
          <div class="dropdown nav-link ">
            <button class="dropbtn dropdown-toggle"><%= t 'menu.bond.bond' %></button>
              <div class="dropdown-content">
              <% if user_signed_in? && current_user.role == 'admin' %>
                <%= link_to t('menu.bond.add_bond'), bonds_path, class:"nav-link" %>             
              <% end %>
              <% if user_signed_in? %>
                <%= link_to t('menu.bond.collection'), bond_collection_index_path, class:"nav-link" %> 
              <% end %>                
            </div>
          </div>
        <% end %>
      </li>
      <% if user_signed_in? && (current_user.role == 'admin' || current_user.role == 's_user') %>
        <li>          
              <div class="dropdown nav-link">
                <button class="dropbtn dropdown-toggle"><%= t 'menu.future.future' %></button>
                  <div class="dropdown-content">
                    <%= link_to t('menu.future.note_future'), note_future_index_path, class:"nav-link" %>
                    <%= link_to t('menu.future.note_future_list'), note_future_list_path, class:'nav-link' %>             
                  </div>
              </div>        
        </li>
      <% end %>
      <% if user_signed_in? && current_user.role == 'admin' %>
        <li>
          <div class="dropdown nav-link">
            <button class="dropbtn dropdown-toggle">Customer</button>
            <div class="dropdown-content">
              <%= link_to "Customer", customers_path, class:"nav-link" %>
              <%#= link_to t('menu.future.note_future_list'), note_future_list_path, class:'nav-link' %>
            </div>
          </div>
        </li>
      <% end %>
        <li class="nav-item"> 
          <% if user_signed_in? && current_user.role == 'admin' %>
            <div class="dropdown nav-link ">
              <button class="dropbtn dropdown-toggle"><%= t 'menu.set.set' %></button>
                <div class="dropdown-content">
                  <%= link_to t('menu.set.reports'), reports_path, class:"nav-link" %>  
                  <%= link_to "Continents", continents_path, class:"nav-link" %>
                  <%= link_to (render 'renders/icon_chart') + t('menu.set.chart'), reports_chart_path, class:"nav-link" %>
                  <%= link_to (render 'renders/icon_chart') + t('menu.set.set_chart'), charts_path, class:"nav-link" %>
                  <hr class="my-1">
                  <%= link_to t('menu.set.pattern'), patterns_path, class:"nav-link" %>
                  <%= link_to t('menu.set.bought'), boughts_path, class:"nav-link" %>
                  <%= link_to t('menu.set.signature_cod'), signatures_path, class:"nav-link" %>
                  <%= link_to "Settings", settings_path, class:"nav-link" %>
                  <%= link_to "Currency Unit", currency_units_path, class:"nav-link" %>
                  <%= link_to "GoldApi", goldapi_index_path, class:"nav-link" %>
                </div>
            </div>
          <% end %>
        </li>      
      <li class="nav-item">
      	<%= link_to 'About PECUNIA', home_about_path, class:"nav-link" %>
      </li>      
    </ul>

    <ul class="navbar-nav ms-auto mb-2 mb-lg-0 center-button ">
        <% if user_signed_in? %>
            <li class= "navbar-brand">
              <%= current_user.role %>
            </li>        
              <li class="nav-item">
                <%= link_to current_user.email, edit_user_registration_path, class:"nav-link" %>
              </li>            
            <li class="nav-item">
              <%= button_to "Logout", destroy_user_session_path, method: :delete, class:"btn btn-sm btn-outline-secondary"  %>
            </li>
        <% else %>
          <li class="nav-item"> 
            <%= link_to "Sign Up", new_user_registration_path, class:"nav-link" %>
          </li> 
          <li class="nav-item"> 
            <%= link_to "Sign In", new_user_session_path, class:"nav-link" %>
          </li> 
        <% end %>
      </ul> 
  </div>
</nav>

app/views/home/_logo.html.erb
<% @root_path = Rails.root.join('app', 'assets', 'images','flags') %>
<div class="container row">
	<div class="logo-center col-md-2">
		<%= image_tag("header/logo.png", :alt => "rss feed" , :size => "100x100", class:"rounded-circle")%>
		<br/>
	</div>
	<div class="logo-center col-md-7">
	    <h1>PECUNIA <small>BANKNOTES OF WORLD</small></h1>
    </div>
	<div class="logo-center col-md-2">
		<%= image_tag("header/logo.png", :alt => "rss feed" , :size => "100x100", class:"rounded-circle") %>
	</div>
	<div class=" col-md-1">
		<div style="font-size:10px">
			<div style="padding:2px">  	
				<% if (File.exist?(@root_path + 'Poland.png')) %>
					<div style="padding:0px">
						<%= link_to (image_tag("flags/" + "Poland.png", :alt => "polish", style:"height:15px" )), url_for(locale: :pl) %>
					</div>
				<% else %>
					<div class="country-flag">
						<%= image_tag("flags/test.png", :alt => "rss feed" , class:"size-flag") %>
					</div>
				<% end %>
			</div> 

 <%#= link_to 'Polish', url_for(locale: :pl) %>

			<div style="padding:2px">  	
				<% if (File.exist?(@root_path + 'England.png')) %>
					<div style="padding:0px">
						<%= link_to (image_tag("flags/" + "England.png", :alt => "english", style:"height:15px" )), url_for(locale: :en) %>
					</div>
				<% else %>
					<div class="country-flag">
						<%= image_tag("flags/test.png", :alt => "rss feed" , class:"size-flag") %>
					</div>
				<% end %>
			</div> 

 <%#= link_to 'English', url_for(locale: :en) %>

			
		</div>
	</div>

</div>

app/views/home/about.html.erb
<h1 style="text-align: center">PECUNIA wersja testowa </h1>
<br/>
<h3>Aplikacja testowa</h3>
<h4>Rejestracja:</h4>
<span>- daje możliwość dostępu do kilku opcji, które z czasem będzie przybywać...</span><br/>
<span>- email: pecunia-adv@gmail.com</span>
test

app/views/home/index.html.erb
<%#= render 'home/api_metal' %>

<div class="container">
  <div class="row">
    <div class="col-4" style="float: right">
      <div style=" margin:10px;">
        <a href="https://www.leftovercurrency.com/" style="color:black">
          <%= image_tag("header/leftover-currency-logo.png", :alt => "Leftover currency" ,
                        style:"max-width:70%; min-width:100px; background-color: lightgrey; padding:10px")%>
        </a>
      </div>
      <%= link_to "Rate Gold",root_path, {class:"btn btn-primary btn-sm", style:"background: green; color:black" , 'data-toggle' => "modal", 'data-target' => "#staticBackdrop"} %>
    </div>
    <div class="col-4">
      <% if @response_code =="200" %>
        <span style="font-size: small">Data: <%= @exchange.effectiveDate %></span>
          <table class="table table-striped table-bordered table-hover table-sm" style="font-size: small; background: darkgray">
            <thead class="thead-dark">
                <tr>
                    <th>Waluta</th>
                    <th>Kod</th>
                    <th>Sredni</th>
                </tr>
            </thead>
            <% @exchange.rates.each do |rate| %>
                <tr>
                    <td><%= rate.currency %></td>
                    <td><%= rate.code %></td>
                    <td><%= rate.mid %></td>
                </tr>
            <% end %>

          </table>
      <% else %>
        <B>KOD-</B><%=@response_code %>
      <% end %>
    </div>
  </div>

  <div style="text-align: center">
    <h4>"Niepodległość"</h4>
    <img style="max-width:25%; max-width: 300px" src="https://pehkkw.ch.files.1drv.com/y4muxeaNpoJz-ILuHG-1AwPz2sUN-zN6vmaoPHFwe24M0ZgZ5xrxfU8XxpR7ANJ1Lom-p8XP_bCIeoRib6qacOJzBA1ZOQkX0WlbBNOccJD7V38GjEizFoiqAR1CzqbL_OtiXJmWz5TWjCmQvqMAto6IDPwWpsZNf0xBAfEBC-kwrPqVvVr6DR4um6oROlMjnPwSVUD7xhgtRPOb6pBhZJJ9A/Poland_20_Zlotych_201a_2018.jpg?psid=1">
    <img style="max-width:25%; max-width: 300px" src="https://pehkkw.ch.files.1drv.com/y4mPUbTFUvHbOBFzyXzwYt9vmStv09xK42uSKR9Yf-WqCius38bsURQs6oUC3Yy_MoNzxlsr6oXrUTm33vcC0NsZW3yxDs84VpdiWwJ4mdC_9cxlEFc_2uS1XqFCautZuLeQ6F_iZjih6rSp_-sqLE19BxKQu61mMgPnTL64VfbvKxKYR71h3ujRfU63e9n0OTt6mAF_nxZPu_5j0ZqQQWCqA/Poland_20_Zlotych_201b_2018.jpg?psid=1">
  </div>
  <div class="modal fade" id="staticBackdrop" data-backdrop="static" data-keyboard="false" tabindex="-1" aria-labelledby="staticBackdropLabel" aria-hidden="true")>
    <div class="modal-dialog modal-dialog-scrollable">
      <div class="modal-content" style="background: lightgray">
        <div class="modal-header">
          <h5 class="modal-title" id="staticBackdropLabel">KURS Złota</h5>
          <button type="button" class="close" data-dismiss="modal" aria-label="Close">
            <span aria-hidden="true">&times;</span>
          </button>
        </div>
        <div class="modal-body">
          <div>
<!--            <span style="text-align: center">Kurs Złota</span>-->
            <% if @response_code_gold == "200"  %>
              <table class="table table-striped table-bordered table-hover table-sm" style="max-width: 100%; min-width: 30%; font-size: small; background: darkgray">
                <thead class="thead-dark">
                <tr>
                  <th>Data</th>
                  <th>Cena/gr</th>
                  <th>Cena/oz</th>
                  <th>Zmiana</th>
                </tr>
                </thead>
                <% @rate_gold.each do |rate| %>
                  <tr>
                    <td><%= rate.date %></td>
                    <td><%= number_to_currency(rate.price_for_gram, unit:"zł", precision: 2, format: "%n %u") %></td>
                    <td><%= number_to_currency(rate.price_for_ounce, unit:"zł", precision: 3, format: "%n %u") %></td>
                    <td class="<%= rate.change > 0 ? 'up' : 'down' %>" style="background-color: #151515" align="right">
                      <%= number_to_currency(rate.change, unit:"%", precision: 3, format: "%n%u") %>
                      <%= rate.change > 0 ? (render 'renders/icon_arrow_up') : (render 'renders/icon_arrow_down') %>
                    </td>
                  </tr>
                <% end %>

              </table>
            <% else %>
              <B>KOD-</B><%=@response_code_gold %>
            <% end %>
          </div>


        </div>
        <div class="modal-footer">
          <button type="button" class="btn btn-secondary btn-sm" data-dismiss="modal">Close</button>
        </div>
      </div>
    </div>
  </div>
</div>