config/routes.rb
Rails.application.routes.draw do

  scope "(:locale)", locale: /#{I18n.available_locales.join("|")}/ do
  
    resources :signatures
    get 'coin_new/index'
    get 'note_new/index'
    resources :boughts
    resources :patterns
    resources :bonds
    devise_for :users
    # get 'note_collection/index'
    # get 'note_for_sell/index'
    # get 'note_for_sell/show'
    # get 'note_collection/show'
    get 'note_collection/show_currency/:id', to: 'note_collection#show_currency', as: 'show_currency'
    get 'note_collection/show_note/:id', to: 'note_collection#show_note', as: 'show_note'
    get 'note_collection/show_note_user/:id', to: 'note_collection#show_note_user', as: 'show_note_user'
    get 'note_collection/back_show_currency/:id', to: 'note_collection#back_show_currency', as: 'back_show_currency'
    get 'note_collection/show_all_notes/:id', to: 'note_collection#show_all_notes', as: 'show_all_notes'

    get 'note_collection/back_to_country_note_collection/:continent', to: 'note_collection#back_to_country_note_collection', as: 'back_to_country_note_collection'


    
    
    # get 'home/index'
    root 'home#index'
    get 'home/about'
    get 'reports/chart'

    get 'currencies/new/country/currency'

    resources :reports
    resources :countries
    resources :currencies
    resources :notes
    resources :note_for_sell, only: [:index, :show]
    resources :note_sold, only: [:index, :show]
    resources :note_new, only: [:index, :show]
    resources :coin_new, only: [:index, :show]
    resources :note_collection, only: [:index, :show]
    resources :coin_for_sell, only: [:index, :show]
    resources :note_future, only: [:index, :show]
    resources :coin_collection, only: [:index, :show]
    resources :bond_collection, only: [:index, :show]
    get 'coin_collection/show_coins/:id', to: 'coin_collection#show_coins', as: 'show_coins'
    get 'coin_collection/show_details_coin/:id', to:'coin_collection#show_details_coin', as: 'show_details_coin'
    get 'coin_collection/show_coin_user/:id', to: 'coin_collection#show_coin_user', as: 'show_coin_user'
    get 'coin_collection/back_show_currency_coin/:id', to: 'coin_collection#back_show_currency_coin', as: 'back_show_currency_coin'
    

    resources :notes
    get 'notes/note_currencies/:id', to: 'notes#note_currencies', as: 'note_currencies'
    get 'notes/note_show_currency/:id', to: 'notes#note_show_currency', as: 'note_show_currency'
    get 'note_search', to: 'notes#note_search'

    resources :coins
    get 'coins/coin_currencies/:id', to: 'coins#coin_currencies', as: 'coin_currencies'
    get 'coins/coin_show_currency/:id', to: 'coins#coin_show_currency', as: 'coin_show_currency'
    get 'coins/new/:id', to: 'coins#new', as: 'new'
    get 'coin_search', to: 'coins#coin_search'

    # BONDS
  
    get 'bonds/bond_currencies/:id', to: 'bonds#bond_currencies', as: 'bond_currencies'
    get 'bonds/bond_show_currency/:id', to: 'bonds#bond_show_currency', as: 'bond_show_currency'
    get 'bond_search', to: 'bonds#bond_search'

    get 'bond_collection/show_bonds/:id', to: 'bond_collection#show_bonds', as: 'show_bonds'
    get 'bond_collection/back_show_currency_bond/:id', to: 'bond_collection#back_show_currency_bond', as: 'back_show_currency_bond'
    get 'bond_collection/show_bond_user/:id', to: 'bond_collection#show_bond_user', as: 'show_bond_user'


    # get 'bond_collection/show_details_bond/:id', to:'bond_collection#show_details_bond', as: 'show_details_bond'  

    # Note for sell
    get 'note_for_sell_list', to: 'note_for_sell#note_for_sell_list'

    # Note Future
    get 'note_future_list', to: 'note_future#note_future_list'
    get 'note_future/show_note_future/:id', to: 'note_future#show_note_future', as: 'show_note_future'


    resources :countries do
      resources :currencies
    end 

    get 'country_search', to: 'countries#country_search'

    resources :currencies do
      resources :notes
    end  

    resources :currencies do
      resources :coins
    end  
    
    resources :currencies do
      resources :bonds
    end

    resources :charts

    resources :customers
    resources :customers do
      resources :orders
    end

    resources :orders
    resources :settings

    resources :order_items
    resources :orders do
      resources :order_items
    end

    get 'order_items/:id_item/item_pattern/:pattern', to: 'order_items#new', as: 'order_item_pattern'
    get 'order_items_for_sell', to: 'order_items#for_sell'

    # get 'goldapi/index'
    resources :goldapi, only: [:index]

    resources :continents
    resources :currency_units
    resources :countries do
      resources :currency_units
    end

    mount ReportsKit::Engine, at: '/'

  end  
    # APi controller
  
    namespace :api do 
      namespace :v1 do
        resources :country, only: [:index, :show]  
        resources :currencies
      end    
    end
end

app/controllers/coin_collection_controller.rb
class CoinCollectionController < ApplicationController
    before_action :require_user_logged_in!
    include CountriesHelper

    def index
        if current_user.role == 'admin'
            @countries = get_countries_coin_colection("KOLEKCJA")
        else
            @countries = get_countries_coin_visible_colection("KOLEKCJA", true)
        end

        @countries.each do |c|
            puts c.country_en
        end
    end

    def show
        puts "&&&&&&&&&&&&&&&&&&&&&&&&& TEST &&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&"
        puts params[:id]
        if current_user.role == 'admin'
            @currencies  = Currency.joins(:coins).where(coins: {status: "KOLEKCJA"},country_id: params[:id], pattern: 'COIN' ).group(:id).order(currency_series: :asc)
        else
            @currencies  = Currency.joins(:coins).where(coins: {status: "KOLEKCJA", visible: true},country_id: params[:id], pattern: 'COIN' ).group(:id).order(currency_series: :asc)
        end

        if @currencies.length != 0
            @country = @currencies[0].country
        else
            redirect_to root_path, alert: "ERROR 404!!!"
        end

    end

    def show_coins
        puts "&&&&&&&&&&&&&&&&&&&&&&&&& SHOW COINS &&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&"
        puts params[:id]
        if current_user.role == 'admin'
            @coins = Coin.where(currency_id: params[:id], status: 'KOLEKCJA').order(denomination: :asc).order(coin_date: :asc)
        else
            @coins = Coin.where(currency_id: params[:id], status: 'KOLEKCJA', visible: true).order(denomination: :asc).order(coin_date: :asc)
        end
        if @coins.size != 0
            @country = @coins[0].currency.country
        else
            redirect_to root_path, alert: "ERROR 404!!!"
        end
    end

    def back_show_currency_coin
        puts params[:id]        
        @currency = Currency.find(params[:id])
        puts @currency.inspect
        redirect_to coin_collection_path(@currency.country_id)
      end

    def show_details_coin
        @coin = Coin.find(params[:id])
    end

    def show_coin_user
        puts "&&&&&&&&&&&&&& SHOW COIN USER &&&&&&&&&&&&&&&&&&&"
        puts params[:id]
        @coin = Coin.find(params[:id])  
        # @country = @coin.currency.country
        if @coin != nil && current_user.role == 'admin'
            @country = @coin.currency.country
        elsif @coin == nil || @coin.status != 'KOLEKCJA' || @coin.visible == false
            redirect_to root_path, alert: "ERROR 404!?!?! \n (" + params[:id].to_s + ")"
        else
            @country = @coin.currency.country
        end
        puts "&&&&&&&&&&&&&& END &&&&&&&&&&&&&&&&&&&&&&&&&&"
      end

end

app/helpers/coin_collection_helper.rb
module CoinCollectionHelper
end

app/views/coin_collection/_coin_modal.erb
<div class="modal-dialog modal-xl" style="max-width: 100%">
  <div class="modal-content">
    <div class="modal-header" style="background: lightgray; padding: 0">
      <div class="container modal-title center-row" id="staticBackdropLabel" >
        <div class="container " style="max-width: 500px; min-width: 150px; padding: 0">
          <% @country = coin.currency.country %>
          <%= render 'renders/show_flag_country' %>
        </div>

        <div class="container modal-title" id="staticBackdropLabel" style="width: 100%" >
          <strong>
            <%= t('activerecord.attributes.currency.currency_series') + ': ' %>
          </strong>
          <%= coin.currency.currency_series %> |
          <%= render 'renders_item/denomination', item: coin %>|
          <b><%= t('activerecord.attributes.coin.coin_date') + ":" %></b> <%= coin.coin_date %> |
          <%#= render 'note_for_sell/note_dimension', note: note %>
        </div>

      </div>
      <button type="button" class="close" data-dismiss="modal" aria-label="Close">
        <span aria-hidden="true">&times;</span>
      </button>
    </div>
    <div class="modal-body" style="background: black">
      <%= image_tag(image, :alt => "REVERSE" , style:"max-height: 700px; max-width: 100%") %>
    </div>
    <div class="modal-footer" style="background: lightgray; display: flow-root; padding: 0">
      <%#= link_to (render 'renders/button_edit'), edit_note_path(note), {class:"btn btn-primary btn-sm", 'onclick' => "myFunction()" } %>
      <button type="button" class="btn btn-sm btn-secondary" data-dismiss="modal" style="float: right" ><%= render ('renders/button_close')%></button>
    </div>
  </div>
</div>

app/views/coin_collection/_show_coin.html.erb
<% if  defined?(coin) %>
  <%@coin = coin %>
<% end %>
  <div class="row row-cols-1 row-cols-sm-2 row-cols-md-4">
    <div class="col">
      <strong>Currency Series: </strong> <%= @coin.currency.currency_series %><br/>
      <strong>Coin Id: </strong><%= @coin.id %>
    </div>
    <div class="col">
      <%= render 'renders/data_ad', dateAdMod: @coin %>
    </div>
  </div>
  <h1 class="display-4" id="notice"></h1>
  <div class="container">

    <div class="row row-cols-1 row-cols-sm-2 row-cols-md-4", style="font-size: small;">
    <% if user_signed_in? && current_user.role == 'admin' %>
      <div class="col p-0">
        <strong>Data zakupu:</strong>
        <%= @coin.date_buy %>
      </div>  
      <div class="col p-0">
        <strong>Miejsce zakupu:</strong>
        <%= @coin.bought %>
      </div>
      <div class="col p-0">
        <strong>cena zakupu:</strong>
        <%= @coin.price_buy.to_s + "zł" %>
      </div>
      
      <div class="col p-0">
        <strong>Cena:</strong>
        <%= @coin.price_sell.to_s + "zł" %>
      </div>         
    <% end %>
      <div class="col p-0">
        <strong>Nominał:</strong>
        <%= number_with_delimiter(@coin.denomination, delimiter: " ") %>
      </div>
      <div class="col p-0">
        <strong>Nazwa waluty:</strong>
        <%= @coin.name_currency %>
      </div>
      <div class="col p-0">
        <strong>Data:</strong>
        <%= @coin.coin_date %>
      </div>
      <div class="col p-0">
        <strong>SERIA:</strong>
        <%= @coin.series %>
      </div>
      <div class="col p-0">
        <strong>Signature code:</strong>
        <%= @coin.signature_code %>
      </div>
    
      
      <div class="col p-0">
        <strong>Ilość:</strong>
        <%= @coin.quantity %> <%= @coin.unit_quantity %>
      </div>
      <div class="col p-0">
        <strong>Stan banknotu:</strong>
        <%= @coin.quality %>
      </div>
      <div class="col p-0">
        <strong>Materiał:</strong>
        <%= @coin.composition %>
      </div>

      <% if (@coin.diameter != nil) %>
        <div class="col p-0">
          <strong>Diameter:</strong>
          <%= @coin.diameter.to_s + " mm" %>
        </div>
      <% end %>
      
      <% if (@coin.thickness != nil) %>
        <div class="col p-0">
          <strong>Thickness:</strong>
          <%= @coin.thickness.to_s + " mm" %>
        </div>
      <% end %>

      <% if (@coin.weight != nil) %>
        <div class="col p-0">
          <strong>Weight:</strong>
          <%= @coin.weight.to_s + " gr" %>
        </div>
      <% end %>

      <div class="col p-0">
        <strong>typ obrazka:</strong>
        <%= @coin.img_type %> 
      </div>
      <div class="col p-0">
        <strong>Status:</strong>
        <%= @coin.status %>
      </div>
      <% if (@coin.status_sell != "") %>
        <% if user_signed_in? && current_user.role == 'admin' %>
          <div class="col p-0">
              <strong>Status sprzedaży:</strong>
              <%= @coin.status_sell %>
          </div>
        <% end %>
      <% end %>
      <div class="col p-0" style="background: orange">
        <% if user_signed_in? && current_user.role == 'admin' %>
          <strong >Visible: </strong><%= @coin.visible %>
        <% end %>
      </div>
    </div>
  </div>
  <p>
    <strong>Description:</strong>
    <%= @coin.description %>
  </p>
  <hr class="my-1">

<% if  defined?(coin) %>
  <%@coin = coin %>
  <div class="row">
    <div class="col col-lg-6 center-row">
      <img src=<%= coin.avers_path %>, class="hover-shadow image-size-show">
    </div>
    <div class="col col-lg-6 center-row">
      <img src=<%= coin.reverse_path %>, class="hover-shadow image-size-show">
    </div>
  </div>
<% else %>
  <% @avers = @coin.avers_path %>
  <% @reverse = @coin.reverse_path %>
  <%= render 'renders/show_image_lightbox' %>
<% end %>

app/views/coin_collection/_show_coin_modal.erb
<div class="modal-dialog modal-xl" style="max-width: 100%">
  <div class="modal-content">
    <div class="modal-header" style="background: lightgray; padding: 0">
      <div class="container modal-title center-row" id="staticBackdropLabel" style="max-width: 500px; min-width: 150px">
        <% @country = coin.currency.country %>
        <%= render 'renders/show_flag_country' %>

      </div>
      <button type="button" class="close" data-dismiss="modal" aria-label="Close">
        <span aria-hidden="true">&times;</span>
      </button>
    </div>
    <div class="modal-body">
      <%= render 'coin_collection/show_coin', coin: coin %>
    </div>
    <div class="modal-footer" style="background: lightgray; display: flow-root; padding: 0">
      <% if user_signed_in? && current_user.role == 'admin' %>
        <%= link_to (render 'renders/button_edit'), edit_coin_path(coin), {class:"btn btn-primary btn-sm", 'onclick' => "myFunction()" } %>
      <% end %>
      <button type="button" class="btn btn-sm btn-secondary" data-dismiss="modal" style="float: right" ><%= render ('renders/button_close')%></button>
    </div>
  </div>
</div>

app/views/coin_collection/index.html.erb
<h2>PAŃSTWA</h2>
<% @root_path = Rails.root.join('app', 'assets', 'images','flags') %> 
<div class="container background-flags ">
  <div class="row row-cols-1 row-cols-sm-2 row-cols-md-4 row-cols-lg-6">
  	<% @countries.each do |country| %>
  	<div class="col position-flag" >  	
    	<%= link_to country.country_en, coin_collection_path(country) %>
  		<% if (File.exist?(@root_path + (country.country_en + '.png'))) %>
		  <div class="country-flag">
        	<%= image_tag("flags/" + country.country_en + ".png", :alt => country.country_en , class:"size-flag") %>
		  </div>
        <% else %>
			<div class="country-flag">
				<%= image_tag("flags/test.png", :alt => "rss feed" , class:"size-flag") %>
			</div>
    	<% end %>
  	</div> 
  	<% end %>
  </div>
</div> 

app/views/coin_collection/show.html.erb
<div class="container">
	<div class="container row">
		<div class="col-md-2">
			<%= link_to (render 'renders/button_back'), coin_collection_index_path, class:"btn btn-secondary btn-sm" %> 
			<h3>WALUTY</h3>
		</div>
		<div class="col-md-8">
			<%= render 'renders/show_flag_country' %>
		</div>			
		<div class="col-md-2">
		</div>
	</div>	
</div>
<div class="row row-cols-1 row-cols-sm-2 row-cols-md-4 row-cols-lg-6 center-row">
	<% @currencies.each do |currency| %>
		<div class="col btn btn-secondary btn-sm logo-center" style="margin:10px;">
			<%= link_to (currency.id.to_s + " - " + currency.currency_series.to_s), show_coins_path(currency), style:"color:black; margin:10px; padding:10px" %>
			
		</div>
	<% end %>
</div>

app/views/coin_collection/show_coin_user.html.erb
<p id="notice"><%= notice %></p>

<div class="jumbotron">
<div class="container row">
		<div class="col-md-2">
		</div>
		<div class="col-md-8">
			<%= render 'renders/show_flag_country' %>
		</div>			
		<div class="col-md-2">
		</div>
</div>
  <%= render 'coin_collection/show_coin' %>
  <div>
    <% if user_signed_in? && current_user.role == 'admin' %>
      <div style="float: left">
        <%= link_to (render 'renders/button_back'), coin_show_currency_path(@coin.currency_id), class:"btn btn-secondary btn-sm" %> 
        <%= link_to (render 'renders/button_edit'), edit_coin_path(@coin), class:"btn btn-primary btn-sm" %> 
      </div>
    <% end %>
    <div style="float:right">
      <%= link_to (render 'renders/button_back'), show_coins_path(@coin.currency_id), class:"btn btn-outline-info btn-sm" %> 
    </div>
   </div>
</div>

app/views/coin_collection/show_coins.html.erb
<div class="container row">
		<div class="col-md-2">
      <%= link_to (render 'renders/button_back'), back_show_currency_coin_path(@coins[0].currency_id), class:"btn btn-secondary btn-sm", style:"float:left" %><br/>
			<h3>Monety</h3>
		</div>
		<div class="col-md-8">
			<%= render 'renders/show_flag_country' %>
		</div>			
		<div class="col-md-2">
		</div>
</div>

<div class="container row" style="text-align: center ">
    <% @coins.each do |coin| %> 
        <div class="col-lg-3 col-md-4 col-sm-6 col-xs-12 primary-container" >
            <div class="image-out-container" >
                <div class="row image-container" >
                    <div class="item">
<!--                      <img class="img-responsive image-collection_size" src=<%#= coin.avers_path %>, alt, = <%#= coin.avers_path %>>-->
                      <% if (coin.avers_path.length > 200) %>
                        <%= link_to (image_tag(coin.avers_path, :alt => "AVERSE", class:"img-responsive image-collection_size")), show_coin_user_path(coin),
                                    {'data-toggle' => "modal", 'data-target' => "#" + "CC-A"+ coin.id.to_s} %>
                        <div class="modal fade" id=<%= "CC-A" + coin.id.to_s %> data-backdrop="static" data-keyboard="false" tabindex="-1" aria-labelledby="staticBackdropLabel">
                          <%= render 'coin_modal', image: coin.avers_path, coin: coin %>
                        </div>
                      <% else %>
                        <%= coin.avers_path %>
                      <% end %>
                    </div>
                    <div class="item">                      
<!--                        <img class="img-responsive image-collection_size" src=<%#= coin.reverse_path %>, alt, = <%#= coin.reverse_path %>>-->
                      <% if (coin.avers_path.length > 200) %>
                        <%= link_to (image_tag(coin.reverse_path, :alt => "REVERSE", class:"img-responsive image-collection_size")), show_coin_user_path(coin),
                                    {'data-toggle' => "modal", 'data-target' => "#" + "CC-B"+ coin.id.to_s} %>
                        <div class="modal fade" id=<%= "CC-B" + coin.id.to_s %> data-backdrop="static" data-keyboard="false" tabindex="-1" aria-labelledby="staticBackdropLabel">
                          <%= render 'coin_modal', image: coin.reverse_path, coin: coin %>
                        </div>
                      <% else %>
                        <%= coin.reverse_path %>
                      <% end %>
                    </div>
                    <div class="item-collection-info" style="margin-top: 10%">
                      <%= t('activerecord.attributes.coin.coin_date') + ': ' %> <%= coin.coin_date %><br/>
                      <% if (coin.denomination != nil) %>
                        <%= t('activerecord.attributes.coin.denomination') + ': ' %> <%= number_with_delimiter(coin.denomination, delimiter: " ") %><br/>
                      <% end %>
                      <%= t('currency') + ': ' %> <%= coin.name_currency %><br/>
                      <% if user_signed_in? && current_user.role == 'admin' %>
                        <strong style="background: orange">Visible: </strong><%= coin.visible %>
                      <% end %>
                      <div class="btn-image-collection" >
                        <%= link_to (render 'renders/button_show'), show_coin_user_path(coin),
                                    {class:"btn btn-outline-info btn-sm", style:"float:left", 'data-toggle' => "modal", 'data-target' => "#" + "CC"+ coin.id.to_s} %>
                        <div class="modal fade" id=<%= "CC" + coin.id.to_s %> data-backdrop="static" data-keyboard="false" tabindex="-1" aria-labelledby="staticBackdropLabel">
                          <%= render 'show_coin_modal', coin: coin %>
                        </div>
                      </div>
                    </div>
                </div>             
            </div>
        </div>
    <% end %>
</div>
<div class="container">
  <%= link_to (render 'renders/button_back'), back_show_currency_coin_path(@coins[0].currency_id), class:"btn btn-secondary btn-sm", style:"float:left" %><br/>
</div>

app/views/coin_collection/show_details_coin.html.erb
<%= render 'renders/show_details_coin' %>